---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: malvados-<ENV>-api
spec:
  selector:
    matchLabels:
      app: malvados-<ENV>-api
  template:
    metadata:
      labels:
        app: malvados-<ENV>-api
    spec:
      initContainers:
        - name: migrate
          image: myhro/malvados:<VERSION>
          command:
            - sh
            - -c
            - cd /app && make migrate
          env:
            - name: POSTGRES_URL
              value: postgres://malvados-<ENV>-postgres/malvados?sslmode=disable
      containers:
        - name: api
          image: myhro/malvados:<VERSION>
          command:
            - /app/api
          env:
            - name: GIN_MODE
              value: release
            - name: POSTGRES_CONN
              value: dbname=malvados host=malvados-<ENV>-postgres sslmode=disable
          ports:
            - containerPort: 8080
