account_id = "779f26d6062518fa03d78247becfd24c"
name = "malvados-v2"
route = "bm.myhro.net/*"
type = "webpack"
workers_dev = false
zone_id = "61d51546beb0253d7f4c005cb3bf7749"

[site]
bucket = "dist"
entry-point = "workers-site"
