---
name: API
"on": [push]
jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - uses: actions/checkout@v1
      - name: Check
        run: |
          make deps
          make lint
  build:
    needs: check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - uses: actions/checkout@v1
      - name: Build
        run: |
          make build
