---
name: WebApp
"on": [push]
jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/checkout@v1
      - name: Check
        run: |
          cd webapp/
          make deps
          make check
          make lint
  build:
    needs: check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/checkout@v1
      - name: Build
        run: |
          cd webapp/
          make deps
          make build
