---
name: WebApp
"on": [push]
jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1
      - name: Check
        run: |
          cd webapp/
          make deps
          make check
          make lint
  build:
    needs: check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1
      - name: Build
        run: |
          cd webapp/
          make deps
          make env
          make build
  deploy:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1
      - name: Deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          cd webapp/
          make deps
          make deploy
